### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by tlg-tg** [PROxZIMA/.dotfiles#10]
One issue I ran into is while trying to install the dots on my laptop is that the hyprland config did not work for some reason and some other configs too. Otherwise would love to install it really nice setup.

**Comment by TheL1nuxGuy** [comment]
Had to go onto my phone account rn but figured out there is an error in the hyperland.conf with decoration settings.

**Comment by PROxZIMA** [comment]
I'm back from the dead. The issue was in `decoration.blur`
