### ISSUE TITLE
Cava not displaying bars in waybar

### ISSUE THREAD

**Issue by WorldTeacher** [PROxZIMA/.dotfiles#11]
Hi, 

I've recently switched to hyprland and found your dotfiles and decided to use them as part of my rice. I especially wanted the custom/music part of your waybar config.jsonc, so I added it to my config file, and copied the caway script to the .scripts dir. 
I have however noticed that unlike in your setup, the bars do not appear, instead the title is staying on display. Do you have any idea why that might be?

This is the snippet of custom/music, I used in my waybar.jsonc:
```
"custom/music": {
         "format": " {icon} {}",
         "format-icons": {
             //"Playing": " ", // Uncomment if not using the dynamic script
             "Paused": "⏸",
             "Stopped": "&#x202d;ﭥ " // This stop symbol is RTL. So &#x202d; is left-to-right override.
         },
         "escape": true,
         "tooltip": true,
         "exec": "~/.scripts/caway -b 10 -e",
         "return-type": "json",
         "on-click": "playerctl play-pause",
         "on-scroll-up": "playerctl previous",
         "on-scroll-down": "playerctl next",
         "on-click-right": "feishin",
         "max-length": 35
     },
```
caway is detecting the player fine, as when launched in a terminal, displays the {text:...} data

**Comment by LayerCZ** [comment]
You disable the bars with the "-e" argument in exec
