### ISSUE TITLE
Nvim doesn't work or I'm stupid

### ISSUE THREAD

**Issue by GnotAI** [PROxZIMA/.dotfiles#15]
I took out the nvim config so that i can use it to replace mine (doesn't work cause I'm bad at setting it up) but there is no leader key mapped to the config anywhere and even when i map a leader key it doesn't work. Am i doing something wrong?

**Comment by PROxZIMA** [comment]
right now thing around nvim is kinda broken in my .dotfiles.
you can refer https://nvchad.com/docs/quickstart/install for a quick setup
