### ISSUE TITLE
How to Download the Wallpapers

### ISSUE THREAD

**Issue by arpagon** [PROxZIMA/.dotfiles#16]
To download the wallpapers from the Google Photos shared album, follow these steps:

1. **Join the Album**: First, join the shared album [here](https://photos.app.goo.gl/h7EE46K7qDgLpQUv9) to get access to the wallpapers.

2. **Set Up `rclone` for Google Photos**: Make sure `rclone` is configured to access Google Photos. For setup instructions, refer to the [rclone Google Photos documentation](https://rclone.org/googlephotos/).

3. **Download the Wallpapers**: Use the following `rclone` command to copy the wallpapers to your local directory:

   ```bash
   rclone copy -vv --log-file rclone-debug.log "gphotos:/shared-album/やℜ々✗¥`𝕊 ᙎ公𝙻𝙻𝕊/" /opt/$USER/Wallpapers/PROxZIMA/
   ```

   - `-vv`: Enables detailed logging.
   - `--log-file rclone-debug.log`: Saves the log output to `rclone-debug.log` for troubleshooting.

4. **Check Your Local Directory**: The downloaded wallpapers should appear in the specified directory (e.g., `/opt/$USER/Wallpapers/PROxZIMA/`).

This should guide you through joining the album and downloading the wallpapers.

**Comment by arpagon** [comment]
I’m adding this documentation so others don’t struggle with escaping the album name. 😫

**Comment by PROxZIMA** [comment]
Thanks @arpagon for the detailed doc. I'll add it to the readme.

I considered other storage options, but since I have a Pixel 6, Google Photos seemed like the best choice.
