### ISSUE TITLE
All looks like high dpi and low resolution on 1366x768 display

### ISSUE THREAD

**Issue by halt-spesn** [PROxZIMA/.dotfiles#3]
How to fix?

**Comment by kticoder** [comment]
Yes, I have the same problem

**Comment by halt-spesn** [comment]
also some scripts like autostart waybar doesn't autostart

**Comment by kticoder** [comment]
> also some scripts like autostart waybar doesn't autostart

Yep

**Comment by kticoder** [comment]
> How to fix?

Have you tried changing the monitor in the config file?

**Comment by PROxZIMA** [comment]
> All looks like high dpi and low resolution on 1366x768 display

Use `monitor=, preferred, auto, 1` in `hyprland.conf`'s 1st line for better suitability. And yeah hardcoding 1920x1080 was a bad move from my side. 

> also some scripts like autostart waybar doesn't autostart

Can you run the `.script/launch_waybar` script manually? If so then post `/tmp/waybar.log` after the first launch (to see the crash logs).

---

Cheers for the first issue 🎉

**Comment by halt-spesn** [comment]
> > All looks like high dpi and low resolution on 1366x768 display
> 
> Use `monitor=, preferred, auto, 1` in `hyprland.conf`'s 1st line for better suitability. And yeah hardcoding 1920x1080 was a bad move from my side.
> 
> > also some scripts like autostart waybar doesn't autostart
> 
> Can you run the `.script/launch_waybar` script manually? If so then post `/tmp/waybar.log` after the first launch (to see the crash logs).
> 
> Cheers for the first issue 🎉

thanks, monitor resolution fixed, btw, waybar start script works when executing it manually

**Comment by PROxZIMA** [comment]
mhmm, can you check `.config/hypr/autostart` once? Any command which may break  the script in your case?

**Comment by kticoder** [comment]
> mhmm, can you check `.config/hypr/autostart` once? Any command which may break the script in your case?

chmod +x .config/hypr/autostart

He solved my problem.

**Comment by halt-spesn** [comment]
> > mhmm, can you check `.config/hypr/autostart` once? Any command which may break the script in your case?
> 
> chmod +x .config/hypr/autostart
> 
> He solved my problem.

thanks, i will try

**Comment by PROxZIMA** [comment]
> chmod +x .config/hypr/autostart

Can you believe this? https://github.com/PROxZIMA/.dotfiles/commit/d0b6f43a46420c86282ae8cda24ec17dc8dc22ef My goodness!!
