### ISSUE TITLE
How to setup Dual Monitor

### ISSUE THREAD

**Issue by raul203al** [PROxZIMA/.dotfiles#5]
I have a laptop with i7 10750h and 2070 max-q and it doesnt detect my second monitor i followed https://wiki.hyprland.org/Nvidia/

**Comment by PROxZIMA** [comment]
Checkout this too https://wiki.hyprland.org/Configuring/Monitors/

**Comment by raul203al** [comment]
Thanks I fixed it (making a clean install) but I think it wasn't working cause of me setting some variable in the wrong .conf file also the SUPER, esc shortcut for logout with the preset didn't work properly (sometimes didn't show the pop up or not working the restart, etc)  and changin to this route ~/.config/hypr/scripts/wlogout works properly. Thanks for the help and making this public

**Comment by raul203al** [comment]
Other thing is there a way to change the hour from the top bar?

**Comment by PROxZIMA** [comment]
> sometimes didn't show the pop up or not working the restart, etc

Make the script executable using `chmod`. I think I missed that one in readme.

> Other thing is there a way to change the hour from the top bar?

https://github.com/PROxZIMA/.dotfiles/blob/11fe8002ff1018ec7676e4e80670235033a78b7d/.config/waybar/config.jsonc#L231

Change the `%H` to any other relevant formatter.

**Comment by raul203al** [comment]
thanks
