### ISSUE TITLE
Fonts and borders

### ISSUE THREAD

**Issue by rnieuwen** [PROxZIMA/.dotfiles#6]
Love your dotfiles. One question though, I am trying to change the system font that you have set to caskaydia. In lxappearance i can set font optiins such as hinting but incannot choose the font itself. I also tried adding .gtk20rc.mine with another font family and referencing that file in .gtk20rc but this will also not work. Am i missing something obvious here?

Also, i commented out all lines referring to borders in hyprland.comf but borders are still displayed. Is this controlled somewhere else?

**Comment by PROxZIMA** [comment]
for fonts check the hyprland autostart script. GTK font is set there.

application borders are solely handled by hyprland. set the border width to 0 instead of commenting them.

**Comment by rnieuwen** [comment]
Awesome, thanks a lot man!

**Comment by PROxZIMA** [comment]
If the issue is fixed then you can close it :p
