### ISSUE TITLE
How to apply Grub theme and SDDM theme

### ISSUE THREAD

**Issue by FatngatirBilek** [PROxZIMA/.dotfiles#8]
Also lock button doesn't work

**Comment by PROxZIMA** [comment]
- [Grub Theme](https://wiki.archlinux.org/title/GRUB/Tips_and_tricks#Theme)
- [SDDM Theme](https://wiki.archlinux.org/title/SDDM#Theme_settings)
- make the ~/.scripts/lock script as executable using chmod

**Comment by FatngatirBilek** [comment]
Why screenshot not work??

**Comment by FatngatirBilek** [comment]
https://github.com/PROxZIMA/.dotfiles/assets/81058978/64a99b15-208e-45df-a6b3-c4652400474b

**Comment by FatngatirBilek** [comment]
> * [Grub Theme](https://wiki.archlinux.org/title/GRUB/Tips_and_tricks#Theme)
> * [SDDM Theme](https://wiki.archlinux.org/title/SDDM#Theme_settings)
> * make the ~/.scripts/lock script as executable using chmod

Yep I'm so fcking dumb 💀

**Comment by FatngatirBilek** [comment]
Why my playerctl doesn't show up tho?

**Comment by FatngatirBilek** [comment]
so I already fixed the screenshot problem, but I still don't know about the playerctl one

![image](https://github.com/PROxZIMA/.dotfiles/assets/81058978/6b3ac6bb-02cc-47dd-9479-6874350e63fd)

**Comment by PROxZIMA** [comment]
> I still don't know about the playerctl one

Check out `~/.scripts/caway`. Play some music and check its output. My waybar's config uses this script.

**Comment by FatngatirBilek** [comment]
Yesterday when I ran the file it didn't show anything. but suddenly now it shows 
"./caway: line 92: jq: command not found"
"./caway: line 96: jq: command not found"
 I just had to install jq and it worked. Thank you for the support
