### ISSUE TITLE
Two dependency packages were not found

### ISSUE THREAD

**Issue by TaterDoge** [PROxZIMA/.dotfiles#9]
swaylockd cliphist-bin

**Comment by gd03champ** [comment]
I've got the same error|

`
> paru -S swaylockd
:: Resolving dependencies...
error: could not find all required packages:
    swaylockd (target)
`

paru -S swaylock  <- this package is available in aur but swaylockd isn't available.

**Comment by PROxZIMA** [comment]
swaylockd -> swaylock
cliphist-bin -> cliphist
